name: agu2023
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - numpy=1.26.*
  - xarray=2023.11.*
  - pandas=2.1.*
  - pyproj=3.6.*
  - pygmt=0.10.*
  - xrft=1.0.*
  - matplotlib=3.8.*
  - pyvista=0.42.*
  - trame=3.3.*
  - jupyter
  - pip
  # Fatiando packages
  - pooch==1.8.0
  - boule==0.4.1
  - ensaio==0.5.0
  - verde==1.8.0
  - harmonica==0.6.0
  - pip:
    - ppigrf==1.0.2
